# Generated by Django 6.0.6 on 2026-06-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectreview",
            name="rating",
        ),
        migrations.AddField(
            model_name="projectreview",
            name="communication_rating",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectreview",
            name="deadline_rating",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectreview",
            name="teamwork_rating",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectreview",
            name="technical_rating",
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
