# Generated by Django 6.0.6 on 2026-06-21 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("github_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("resume_url", models.URLField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=15)),
                ("show_email", models.BooleanField(default=False)),
                ("show_github", models.BooleanField(default=True)),
                ("show_linkedin", models.BooleanField(default=True)),
                ("show_phone", models.BooleanField(default=False)),
                ("show_resume", models.BooleanField(default=True)),
                ("show_projects", models.BooleanField(default=True)),
                ("show_skills", models.BooleanField(default=True)),
                ("show_profile_picture", models.BooleanField(default=True)),
                ("show_bio", models.BooleanField(default=True)),
                ("show_contributions", models.BooleanField(default=True)),
                ("show_stats", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
